# Idempotent demo seeds: three demo designer accounts, thirty-seven published models.
#
# PROVENANCE (audit trail): every asset under db/seed_assets/ is SELF-AUTHORED —
# parametric solids generated by this repo's seed tooling, published CC0.
# Source: this repository. No externally-sourced files, so no third-party
# license obligations attach to the demo catalog.

ASSETS = Rails.root.join("db/seed_assets")
PROVENANCE = YAML.safe_load_file(ASSETS.join("provenance.yml")).fetch("models")
PROVENANCE_NOTE = "Self-authored parametric model dedicated CC0-1.0; reproducible source and print notes are included with the catalog."

# A published file hash is part of every certificate. If a prior seed asset has
# already sold, keep that model, its offers, and its attachments immutable;
# retire it under a stable legacy slug and publish the replacement separately.
def upgradable_seed_model(slug, file_hash)
  model = Model3d.find_by(slug: slug)
  return Model3d.new(slug: slug) unless model
  return model if model.file_hash.blank? || model.file_hash == file_hash
  return model unless model.license_offers.joins(:purchases).exists?

  model.update!(slug: "#{slug}-legacy-#{model.id}", status: "retired")
  Model3d.new(slug: slug)
end

# Designers with their own funded testnet account (SEED_*_ACCOUNT_ID env)
# receive sales directly once the publish-time mirror check passes; the rest
# demonstrate treasury custody + owed balance. Never default to the treasury
# account here — a designer "owning" the treasury id corrupts held_by.
def demo_designer(email, name, bio, account_env: nil)
  designer = Designer.find_or_create_by!(email_address: email) do |d|
    d.password = SecureRandom.base58(24)
    d.display_name = name
    d.hedera_account_id = account_env && ENV[account_env].presence
    d.verified = true
  end
  designer.update!(bio: "#{bio} Demo catalog geometry is self-authored and dedicated CC0-1.0.")
  designer
end

studio = demo_designer("studio@printwright.demo", "Printwright Demo Studio",
                       "In-house demo studio for functional prints.",
                       account_env: "SEED_STUDIO_ACCOUNT_ID")
atelier = demo_designer("atelier@printwright.demo", "Hexa Atelier",
                        "Decor and desk objects, tuned for clean FDM printing.",
                        account_env: "SEED_ATELIER_ACCOUNT_ID")
workshop = demo_designer("workshop@printwright.demo", "Beaver Workshop",
                         "Toys and articulated figures that print support-free.")

EXTRA_MODELS = [
  { designer: :atelier, slug: "phone-stand", title: "Wedge Phone Stand",
    description: "Low-angle wedge stand for phones and small tablets. Prints flat, no supports.",
    tags: %w[phone stand desk wedge], printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 55, bed_min_mm: 50 },
    category: "desk-organization", collections: %w[support-free-essentials under-an-hour small-space],
    offers: [ { kind: "personal", price_cents: 180, currency: "USDC" } ] },
  { designer: :studio, slug: "cable-clip", title: "Snap Cable Clip",
    description: "Springy open clip for cables up to 16 mm, with a broad mounting pad. Print a dozen at once.",
    tags: %w[cable clip organizer desk], printability: { supports: false, materials: %w[PETG], est_print_minutes: 12, bed_min_mm: 20 },
    category: "desk-organization", collections: %w[support-free-essentials under-an-hour small-space],
    offers: [ { kind: "personal", price_cents: 90, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 25, currency: "USDC" } ] },
  { designer: :atelier, slug: "planter-mini", title: "Mini Cone Planter",
    description: "Palm-sized tapered planter for succulents, with a 6.4 mm drainage hole and sturdy walls.",
    tags: %w[planter succulent decor vase], printability: { supports: false, materials: %w[PLA], est_print_minutes: 80, bed_min_mm: 60 },
    category: "home-and-garden", collections: %w[support-free-essentials small-space],
    offers: [ { kind: "personal", price_cents: 210, currency: "USDC" } ] },
  { designer: :workshop, slug: "dice-d6", title: "Chunky D6 Dice",
    description: "Oversized rounded tabletop die with three recessed faces. A toy and calibration print, not casino-balanced.",
    tags: %w[dice tabletop game toy], printability: { supports: false, materials: %w[PLA ABS], est_print_minutes: 40, bed_min_mm: 25 },
    category: "toys-and-games", collections: %w[support-free-essentials under-an-hour],
    offers: [ { kind: "personal", price_cents: 140, currency: "HBAR" } ] },
  { designer: :studio, slug: "bag-hook", title: "Hex Bag Hook",
    description: "Flat carabiner-style hook with a flexible mouth for decorative and light-duty use.",
    tags: %w[hook bag carry utility], printability: { supports: false, materials: %w[PETG], est_print_minutes: 35, bed_min_mm: 45 },
    category: "home-and-garden", collections: %w[support-free-essentials under-an-hour],
    offers: [ { kind: "personal", price_cents: 160, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 45, currency: "USDC" } ] },
  { designer: :atelier, slug: "vase-spiral", title: "Spiral Bud Vase",
    description: "Slim twelve-sided bud vase with a 105-degree twist and a closed 2.4 mm floor.",
    tags: %w[vase decor spiral flower], printability: { supports: false, materials: %w[PLA], est_print_minutes: 95, bed_min_mm: 50 },
    category: "home-and-garden", collections: %w[support-free-essentials],
    offers: [ { kind: "personal", price_cents: 260, currency: "USDC" } ] },
  { designer: :workshop, slug: "gear-toy", title: "Fidget Gear",
    description: "Ten-tooth fidget gear that mates with itself. Print two.",
    tags: %w[gear fidget toy mechanical], printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 30, bed_min_mm: 45 },
    category: "toys-and-games", collections: %w[support-free-essentials under-an-hour maker-basics],
    offers: [ { kind: "personal", price_cents: 120, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 30, currency: "USDC" } ] },
  { designer: :studio, slug: "wall-bracket", title: "Utility Wall Bracket",
    description: "Screw-mount bracket for lightweight shelving and cable runs.",
    tags: %w[bracket wall mount utility], printability: { supports: true, materials: %w[PETG ABS], est_print_minutes: 65, bed_min_mm: 40 },
    category: "workshop-tools", collections: %w[maker-basics],
    offers: [ { kind: "personal", price_cents: 190, currency: "USDC" } ] },
  { designer: :workshop, slug: "whistle", title: "Emergency Whistle",
    description: "Single-piece pealess signal-whistle prototype. Acoustic performance varies with material and slicer settings.",
    tags: %w[whistle outdoor safety toy], printability: { supports: false, materials: %w[PLA], est_print_minutes: 22, bed_min_mm: 30 },
    category: "toys-and-games", collections: %w[support-free-essentials under-an-hour],
    offers: [ { kind: "personal", price_cents: 110, currency: "HBAR" } ] }
].freeze

DEEP_CATALOG_MODELS = [
  { designer: :studio, slug: "headphone-stand", title: "Headphone Stand",
    description: "Stable T-stand with a broad headband rest and compact rectangular base.",
    tags: %w[headphone stand audio desk], category: "desk-organization", collections: %w[small-space],
    printability: { supports: true, materials: %w[PLA PETG], est_print_minutes: 150, bed_min_mm: 80 },
    offers: [ { kind: "personal", price_cents: 240, currency: "USDC" } ] },
  { designer: :atelier, slug: "pen-tray", title: "Low-Profile Pen Tray",
    description: "Wide open tray with a shallow rim for pens, calipers, and small desk tools.",
    tags: %w[pen tray desk organizer], category: "desk-organization",
    collections: %w[support-free-essentials small-space],
    printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 85, bed_min_mm: 160 },
    offers: [ { kind: "personal", price_cents: 170, currency: "USDC" } ] },
  { designer: :studio, slug: "cable-comb", title: "Four-Lane Cable Comb",
    description: "Open desktop comb that separates four charging or signal cables without a lid.",
    tags: %w[cable comb routing desk], category: "desk-organization",
    collections: %w[support-free-essentials under-an-hour small-space],
    printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 38, bed_min_mm: 90 },
    offers: [ { kind: "personal", price_cents: 110, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 25, currency: "USDC" } ] },
  { designer: :studio, slug: "drawer-label-clip", title: "Drawer Label Clip",
    description: "Open-ended channel for a removable paper label or thin drawer-edge marker.",
    tags: %w[label clip drawer storage], category: "desk-organization",
    collections: %w[support-free-essentials under-an-hour small-space],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 18, bed_min_mm: 60 },
    offers: [ { kind: "personal", price_cents: 80, currency: "USDC" } ] },
  { designer: :studio, slug: "business-card-holder", title: "Business Card Rail",
    description: "Minimal two-rail display stand for standard business cards and small place cards.",
    tags: %w[business card holder display desk], category: "desk-organization",
    collections: %w[support-free-essentials under-an-hour small-space],
    printability: { supports: false, materials: %w[PLA], est_print_minutes: 32, bed_min_mm: 90 },
    offers: [ { kind: "personal", price_cents: 120, currency: "USDC" } ] },
  { designer: :atelier, slug: "soap-dish", title: "Draining Soap Dish",
    description: "Simple perforated platform that lets water escape beneath a bar of soap.",
    tags: %w[soap dish drain bathroom], category: "home-and-garden",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 48, bed_min_mm: 110 },
    offers: [ { kind: "personal", price_cents: 140, currency: "USDC" } ] },
  { designer: :atelier, slug: "plant-trellis", title: "Mini Plant Trellis",
    description: "Flat training frame for lightweight indoor vines and young climbing plants.",
    tags: %w[plant trellis garden vine], category: "home-and-garden",
    collections: %w[support-free-essentials],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 62, bed_min_mm: 140 },
    offers: [ { kind: "personal", price_cents: 130, currency: "USDC" } ] },
  { designer: :atelier, slug: "tealight-lantern", title: "LED Tealight Lantern",
    description: "Perforated shade for cool LED tealights only; never use it with an open flame.",
    tags: %w[lantern led tealight decor], category: "home-and-garden", collections: [],
    printability: { supports: true, materials: %w[PLA PETG], est_print_minutes: 125, bed_min_mm: 76 },
    offers: [ { kind: "personal", price_cents: 220, currency: "USDC" } ] },
  { designer: :atelier, slug: "picture-stand", title: "Small Picture Stand",
    description: "Wide-lipped inclined stand for postcards, signs, and lightweight small frames.",
    tags: %w[picture frame stand display], category: "home-and-garden",
    collections: %w[support-free-essentials small-space],
    printability: { supports: false, materials: %w[PLA], est_print_minutes: 78, bed_min_mm: 100 },
    offers: [ { kind: "personal", price_cents: 160, currency: "USDC" } ] },
  { designer: :atelier, slug: "plant-saucer", title: "Mini Plant Saucer",
    description: "Shallow catch tray for a small pot, with a raised outer rim and solid floor.",
    tags: %w[plant saucer pot garden], category: "home-and-garden",
    collections: %w[support-free-essentials under-an-hour small-space],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 42, bed_min_mm: 72 },
    offers: [ { kind: "personal", price_cents: 100, currency: "USDC" } ] },
  { designer: :atelier, slug: "measuring-scoop", title: "Nominal Measuring Scoop",
    description: "Small handled scoop for dry craft materials; volume is nominal, not certified for food.",
    tags: %w[scoop measure kitchen craft], category: "kitchen-and-dining",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 52, bed_min_mm: 130 },
    offers: [ { kind: "personal", price_cents: 130, currency: "USDC" } ] },
  { designer: :studio, slug: "bag-sealer", title: "Slide-On Bag Sealer",
    description: "Open-ended C-channel for closing the folded edge of a lightweight storage bag.",
    tags: %w[bag sealer clip kitchen], category: "kitchen-and-dining",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PETG], est_print_minutes: 34, bed_min_mm: 160 },
    offers: [ { kind: "personal", price_cents: 90, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 20, currency: "USDC" } ] },
  { designer: :atelier, slug: "hex-coaster", title: "Recessed Hex Coaster",
    description: "Low six-sided coaster with a shallow center and a broad raised rim.",
    tags: %w[coaster hex table drink], category: "kitchen-and-dining",
    collections: %w[support-free-essentials under-an-hour small-space],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 36, bed_min_mm: 90 },
    offers: [ { kind: "personal", price_cents: 100, currency: "HBAR" } ] },
  { designer: :studio, slug: "mini-funnel", title: "Mini Utility Funnel",
    description: "Straight tapered funnel with a 14 mm outlet for dry goods and workshop liquids.",
    tags: %w[funnel pour kitchen workshop], category: "kitchen-and-dining",
    collections: %w[support-free-essentials],
    printability: { supports: false, materials: %w[PETG], est_print_minutes: 64, bed_min_mm: 84 },
    offers: [ { kind: "personal", price_cents: 140, currency: "USDC" } ] },
  { designer: :studio, slug: "tube-squeezer", title: "Flat Tube Squeezer",
    description: "Hand grip with a narrow slot for rolling down flexible household tubes.",
    tags: %w[tube squeezer tool bathroom], category: "workshop-tools",
    collections: %w[support-free-essentials under-an-hour maker-basics],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 30, bed_min_mm: 100 },
    offers: [ { kind: "personal", price_cents: 100, currency: "USDC" } ] },
  { designer: :studio, slug: "spacer-set", title: "Three-Ring Spacer Set",
    description: "Three separate low spacer rings with different bores for fit and setup experiments.",
    tags: %w[spacer washer ring workshop], category: "workshop-tools",
    collections: %w[support-free-essentials under-an-hour maker-basics],
    printability: { supports: false, materials: %w[PETG ABS PLA], est_print_minutes: 24, bed_min_mm: 60 },
    offers: [ { kind: "personal", price_cents: 100, currency: "USDC" } ] },
  { designer: :studio, slug: "corner-jig", title: "Flat 90° Corner Jig",
    description: "Right-angle reference with two clamp holes for light assembly and layout work.",
    tags: %w[corner jig square workshop], category: "workshop-tools",
    collections: %w[support-free-essentials under-an-hour maker-basics],
    printability: { supports: false, materials: %w[PETG PLA], est_print_minutes: 46, bed_min_mm: 80 },
    offers: [ { kind: "personal", price_cents: 150, currency: "USDC" } ] },
  { designer: :studio, slug: "drill-guide", title: "Three-Bore Drill Guide",
    description: "Bench block with nominal 4, 6, and 8 mm vertical bores; verify dimensions before use.",
    tags: %w[drill guide bore workshop jig], category: "workshop-tools",
    collections: %w[support-free-essentials under-an-hour maker-basics],
    printability: { supports: false, materials: %w[PETG ABS], est_print_minutes: 44, bed_min_mm: 80 },
    offers: [ { kind: "personal", price_cents: 160, currency: "USDC" } ] },
  { designer: :studio, slug: "star-knob", title: "Eight-Lobe Star Knob",
    description: "Hand knob with a plain 6 mm bore, ready for user-supplied hardware or a press fit.",
    tags: %w[knob star replacement handle], category: "replacement-parts",
    collections: %w[support-free-essentials under-an-hour maker-basics],
    printability: { supports: false, materials: %w[PETG ABS PLA], est_print_minutes: 28, bed_min_mm: 48 },
    offers: [ { kind: "personal", price_cents: 110, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 25, currency: "USDC" } ] },
  { designer: :studio, slug: "hinge-pin", title: "Nominal 10 mm Hinge Pin",
    description: "Straight pin with a retaining head; tune scale and clearance for the mating hinge.",
    tags: %w[hinge pin replacement repair], category: "replacement-parts",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PETG ABS], est_print_minutes: 20, bed_min_mm: 18 },
    offers: [ { kind: "personal", price_cents: 80, currency: "USDC" } ] },
  { designer: :studio, slug: "furniture-foot", title: "Tapered Furniture Foot",
    description: "Light-duty tapered foot with a plain locating stem; load capacity is not tested.",
    tags: %w[furniture foot replacement repair], category: "replacement-parts",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PETG ABS], est_print_minutes: 48, bed_min_mm: 50 },
    offers: [ { kind: "personal", price_cents: 130, currency: "USDC" } ] },
  { designer: :studio, slug: "hose-adapter", title: "Stepped Hose Adapter",
    description: "Hollow 36-to-28 mm outside-diameter adapter with an 18 mm through-bore.",
    tags: %w[hose adapter fitting replacement], category: "replacement-parts",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PETG ABS], est_print_minutes: 50, bed_min_mm: 36 },
    offers: [ { kind: "personal", price_cents: 150, currency: "USDC" } ] },
  { designer: :workshop, slug: "puzzle-tile", title: "Two-Tab Puzzle Tile",
    description: "Square play tile with two tabs and two matching sockets for open tessellations.",
    tags: %w[puzzle tile game toy], category: "toys-and-games",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 26, bed_min_mm: 66 },
    offers: [ { kind: "personal", price_cents: 90, currency: "USDC" } ] },
  { designer: :workshop, slug: "spinning-top", title: "Classic Spinning Top",
    description: "Single-piece rotational desk top with a broad flywheel and tall finger stem.",
    tags: %w[spinning top toy desk], category: "toys-and-games",
    collections: %w[support-free-essentials under-an-hour],
    printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 32, bed_min_mm: 50 },
    offers: [ { kind: "personal", price_cents: 100, currency: "HBAR" },
              { kind: "commercial_unit", price_cents: 20, currency: "USDC" } ] },
  { designer: :studio, slug: "open-wheel-toy-racer",
    title: "Open-Wheel Toy Racer",
    description: "A compact open-wheel toy car with chunky wheels, raised ground clearance, and simple logo-free bodywork.",
    tags: %w[race car racer open-wheel motorsport formula toy], category: "toys-and-games",
    collections: %w[small-space],
    printability: { supports: true, materials: %w[PLA PETG], est_print_minutes: 62, bed_min_mm: 106 },
    offers: [ { kind: "personal", price_cents: 120, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 35, currency: "USDC" } ] }
].freeze

MODELS = [
  {
    designer: :workshop,
    slug: "beaver-with-hat",
    title: "Beaver Desk Mascot with Hat",
    description: "A cheerful single-piece beaver desk mascot with a flat tail, tiny muzzle, ears, feet, and top hat.",
    tags: %w[beaver hat animal mascot desk toy],
    category: "toys-and-games", collections: [],
    printability: { supports: true, materials: %w[PLA PETG], est_print_minutes: 95, bed_min_mm: 45 },
    stl: "beaver-with-hat.stl", render: "beaver-with-hat.png",
    offers: [
      { kind: "personal", price_cents: 250, currency: "USDC",
        terms_md: "Personal license: print for yourself, unlimited personal copies. No resale of prints or files." },
      { kind: "commercial_unit", price_cents: 60, currency: "USDC",
        terms_md: "Commercial unit license: one licensed sale of one printed unit. Royalty per print run." }
    ]
  },
  {
    designer: :studio,
    slug: "calibration-cube-20mm",
    title: "Calibration Cube 20 mm",
    description: "Nominal 20 mm calibration cube with lightly rounded edges for dialing in dimensional accuracy.",
    tags: %w[calibration cube test benchmark],
    category: "workshop-tools", collections: %w[support-free-essentials under-an-hour maker-basics],
    printability: { supports: false, materials: %w[PLA ABS PETG], est_print_minutes: 25, bed_min_mm: 20 },
    stl: "calibration-cube.stl", render: "calibration-cube.png",
    offers: [
      { kind: "personal", price_cents: 120, currency: "HBAR",
        terms_md: "Personal license: print for yourself, unlimited personal copies." }
    ]
  },
  {
    designer: :atelier,
    slug: "hex-desk-organizer",
    title: "Hexagon Desk Organizer",
    description: "Open hexagonal desk cup with a 3 mm floor and sturdy walls for pens, tools, or brushes.",
    tags: %w[organizer desk hexagon storage cup],
    category: "desk-organization", collections: %w[support-free-essentials small-space],
    printability: { supports: false, materials: %w[PLA], est_print_minutes: 140, bed_min_mm: 30 },
    stl: "hex-organizer.stl", render: "hex-organizer.png",
    offers: [
      { kind: "personal", price_cents: 290, currency: "USDC",
        terms_md: "Personal license: print for yourself, unlimited personal copies." },
      { kind: "commercial_unit", price_cents: 75, currency: "USDC",
        terms_md: "Commercial unit license: one licensed sale of one printed unit." }
    ]
  }
].freeze

DESIGNERS = { studio: studio, atelier: atelier, workshop: workshop }.freeze

(MODELS + EXTRA_MODELS + DEEP_CATALOG_MODELS).each do |spec|
  stl_name = spec[:stl] || "#{spec[:slug]}.stl"
  render_name = spec[:render] || "#{spec[:slug]}.png"
  stl_bytes = ASSETS.join(stl_name).binread
  provenance = PROVENANCE.fetch(File.basename(stl_name, ".stl"))
  raise "Provenance slug mismatch for #{spec[:slug]}" unless provenance.fetch("slug") == spec[:slug]
  file_hash = "sha256:#{Digest::SHA256.hexdigest(stl_bytes)}"

  model = upgradable_seed_model(spec[:slug], file_hash)
  model.assign_attributes(
    designer: DESIGNERS.fetch(spec[:designer]),
    title: spec[:title],
    description: "#{spec[:description]} #{PROVENANCE_NOTE}",
    tags: spec[:tags],
    category: spec[:category],
    collections: spec[:collections],
    printability: spec[:printability],
    file_hash: file_hash,
    status: "published"
  )
  model.save!

  stl_file = model.model_files.find_or_create_by!(kind: "stl", position: 0)
  unless stl_file.file.attached? && stl_file.file.blob.checksum == Digest::MD5.base64digest(stl_bytes)
    stl_file.file.attach(io: StringIO.new(stl_bytes), filename: stl_name, content_type: "model/stl")
  end

  render = model.model_files.find_or_create_by!(kind: "render", position: 1)
  render_bytes = ASSETS.join(render_name).binread
  unless render.file.attached? && render.file.blob.checksum == Digest::MD5.base64digest(render_bytes)
    render.file.attach(io: StringIO.new(render_bytes), filename: render_name, content_type: "image/png")
  end

  PreviewMeshes::Attacher.call(model)
  AnalyzeModelMeshJob.perform_now(model.id)

  spec[:offers].each do |offer_spec|
    offer = model.license_offers.find_or_initialize_by(kind: offer_spec[:kind])
    offer.assign_attributes(offer_spec)
    offer.save!
  end
end

puts "Seeded: #{Designer.count} designers, #{Model3d.count} models, " \
     "#{LicenseOffer.count} offers, #{ModelFile.count} files."
