# Idempotent demo seeds: three demo designer accounts, twelve published models.
#
# PROVENANCE (audit trail): every asset under db/seed_assets/ is SELF-AUTHORED —
# parametric solids generated by this repo's seed tooling, published CC0.
# Source: this repository. No externally-sourced files, so no third-party
# license obligations attach to the demo catalog.

ASSETS = Rails.root.join("db/seed_assets")

def demo_designer(email, name, bio)
  Designer.find_or_create_by!(email_address: email) do |d|
    d.password = SecureRandom.base58(24)
    d.display_name = name
    d.bio = "#{bio} (Demo account; catalog is self-authored CC0 placeholder geometry.)"
    d.hedera_account_id = ENV.fetch("X402_PAY_TO", "0.0.9584959")
    d.verified = true
  end
end

studio = demo_designer("studio@printwright.demo", "Printwright Demo Studio",
                       "In-house demo studio for functional prints.")
atelier = demo_designer("atelier@printwright.demo", "Hexa Atelier",
                        "Decor and desk objects, tuned for clean FDM printing.")
workshop = demo_designer("workshop@printwright.demo", "Beaver Workshop",
                         "Toys and articulated figures that print support-free.")

EXTRA_MODELS = [
  { designer: :atelier, slug: "phone-stand", title: "Wedge Phone Stand",
    description: "Low-angle wedge stand for phones and small tablets. Prints flat, no supports.",
    tags: %w[phone stand desk wedge], printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 55, bed_min_mm: 50 },
    offers: [ { kind: "personal", price_cents: 180, currency: "USDC" } ] },
  { designer: :studio, slug: "cable-clip", title: "Snap Cable Clip",
    description: "Snap-fit cable clip for desk edges up to 25 mm. Print a dozen at once.",
    tags: %w[cable clip organizer desk], printability: { supports: false, materials: %w[PETG], est_print_minutes: 12, bed_min_mm: 20 },
    offers: [ { kind: "personal", price_cents: 90, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 25, currency: "USDC" } ] },
  { designer: :atelier, slug: "planter-mini", title: "Mini Cone Planter",
    description: "Palm-sized planter for succulents; drainage hole included. Vase-mode friendly.",
    tags: %w[planter succulent decor vase], printability: { supports: false, materials: %w[PLA], est_print_minutes: 80, bed_min_mm: 60 },
    offers: [ { kind: "personal", price_cents: 210, currency: "USDC" } ] },
  { designer: :workshop, slug: "dice-d6", title: "Chunky D6 Dice",
    description: "Oversized tabletop die with recessed pips. Balanced infill recommended.",
    tags: %w[dice tabletop game toy], printability: { supports: false, materials: %w[PLA ABS], est_print_minutes: 40, bed_min_mm: 25 },
    offers: [ { kind: "personal", price_cents: 140, currency: "HBAR" } ] },
  { designer: :studio, slug: "bag-hook", title: "Hex Bag Hook",
    description: "Load-tested carabiner-style bag hook. Print solid, 6 walls.",
    tags: %w[hook bag carry utility], printability: { supports: false, materials: %w[PETG], est_print_minutes: 35, bed_min_mm: 45 },
    offers: [ { kind: "personal", price_cents: 160, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 45, currency: "USDC" } ] },
  { designer: :atelier, slug: "vase-spiral", title: "Spiral Bud Vase",
    description: "Slim bud vase; print in spiral/vase mode for a seamless finish.",
    tags: %w[vase decor spiral flower], printability: { supports: false, materials: %w[PLA], est_print_minutes: 95, bed_min_mm: 50 },
    offers: [ { kind: "personal", price_cents: 260, currency: "USDC" } ] },
  { designer: :workshop, slug: "gear-toy", title: "Fidget Gear",
    description: "Ten-tooth fidget gear that mates with itself. Print two.",
    tags: %w[gear fidget toy mechanical], printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 30, bed_min_mm: 45 },
    offers: [ { kind: "personal", price_cents: 120, currency: "USDC" },
              { kind: "commercial_unit", price_cents: 30, currency: "USDC" } ] },
  { designer: :studio, slug: "wall-bracket", title: "Utility Wall Bracket",
    description: "Screw-mount bracket for lightweight shelving and cable runs.",
    tags: %w[bracket wall mount utility], printability: { supports: true, materials: %w[PETG ABS], est_print_minutes: 65, bed_min_mm: 40 },
    offers: [ { kind: "personal", price_cents: 190, currency: "USDC" } ] },
  { designer: :workshop, slug: "whistle", title: "Emergency Whistle",
    description: "Single-piece pea-less whistle. Loud, print-in-place.",
    tags: %w[whistle outdoor safety toy], printability: { supports: false, materials: %w[PLA], est_print_minutes: 22, bed_min_mm: 30 },
    offers: [ { kind: "personal", price_cents: 110, currency: "HBAR" } ] }
].freeze

MODELS = [
  {
    designer: :workshop,
    slug: "beaver-with-hat",
    title: "Articulated Beaver with Hat",
    description: "A cheerful articulated beaver wearing a tiny top hat. Prints support-free; " \
                 "joints snap together off the bed. Demo placeholder geometry (pyramid solid).",
    tags: %w[beaver hat animal articulated flexi toy],
    printability: { supports: false, materials: %w[PLA PETG], est_print_minutes: 95, bed_min_mm: 40 },
    stl: "beaver-with-hat.stl", render: "beaver-with-hat.png",
    offers: [
      { kind: "personal", price_cents: 250, currency: "USDC",
        terms_md: "Personal license: print for yourself, unlimited personal copies. No resale of prints or files." },
      { kind: "commercial_unit", price_cents: 60, currency: "USDC",
        terms_md: "Commercial unit license: one licensed sale of one printed unit. Royalty per print run." }
    ]
  },
  {
    designer: :studio,
    slug: "calibration-cube-20mm",
    title: "Calibration Cube 20 mm",
    description: "Classic 20 mm calibration cube for dialing in your printer. Demo placeholder geometry.",
    tags: %w[calibration cube test benchmark],
    printability: { supports: false, materials: %w[PLA ABS PETG], est_print_minutes: 25, bed_min_mm: 20 },
    stl: "calibration-cube.stl", render: "calibration-cube.png",
    offers: [
      { kind: "personal", price_cents: 120, currency: "HBAR",
        terms_md: "Personal license: print for yourself, unlimited personal copies." }
    ]
  },
  {
    designer: :atelier,
    slug: "hex-desk-organizer",
    title: "Hexagon Desk Organizer",
    description: "Stackable hexagonal desk organizer cell. Chain as many as your desk deserves. " \
                 "Demo placeholder geometry (hex prism).",
    tags: %w[organizer desk hexagon storage stackable],
    printability: { supports: false, materials: %w[PLA], est_print_minutes: 140, bed_min_mm: 30 },
    stl: "hex-organizer.stl", render: "hex-organizer.png",
    offers: [
      { kind: "personal", price_cents: 290, currency: "USDC",
        terms_md: "Personal license: print for yourself, unlimited personal copies." },
      { kind: "commercial_unit", price_cents: 75, currency: "USDC",
        terms_md: "Commercial unit license: one licensed sale of one printed unit." }
    ]
  }
].freeze

DESIGNERS = { studio: studio, atelier: atelier, workshop: workshop }.freeze

(MODELS + EXTRA_MODELS).each do |spec|
  stl_name = spec[:stl] || "#{spec[:slug]}.stl"
  render_name = spec[:render] || "#{spec[:slug]}.png"
  stl_bytes = ASSETS.join(stl_name).binread

  model = Model3d.find_or_initialize_by(slug: spec[:slug])
  model.assign_attributes(
    designer: DESIGNERS.fetch(spec[:designer]),
    title: spec[:title],
    description: spec[:description],
    tags: spec[:tags],
    printability: spec[:printability],
    file_hash: "sha256:#{Digest::SHA256.hexdigest(stl_bytes)}",
    status: "published"
  )
  model.save!

  stl_file = model.model_files.find_or_create_by!(kind: "stl", position: 0)
  unless stl_file.file.attached?
    stl_file.file.attach(io: StringIO.new(stl_bytes), filename: stl_name, content_type: "model/stl")
  end

  render = model.model_files.find_or_create_by!(kind: "render", position: 1)
  unless render.file.attached?
    render.file.attach(io: ASSETS.join(render_name).open, filename: render_name, content_type: "image/png")
  end

  spec[:offers].each do |offer_spec|
    offer = model.license_offers.find_or_initialize_by(kind: offer_spec[:kind])
    offer.assign_attributes(offer_spec)
    offer.save!
  end
end

puts "Seeded: #{Designer.count} designers, #{Model3d.count} models, " \
     "#{LicenseOffer.count} offers, #{ModelFile.count} files."
